<?php

namespace App\Models\Compliance\Recommendation;

use App\Enums\Compliance\Recommendation\ComplianceRecommendationPriority;
use App\Enums\Compliance\Recommendation\ComplianceRecommendationStatus;
use App\Models\Compliance\ComplianceControl;
use App\Models\Compliance\ComplianceCorpusRevision;
use App\Models\Compliance\ComplianceDomain;
use App\Models\Compliance\ComplianceFrameworkRelease;
use App\Models\Compliance\ComplianceRequirement;
use App\Models\Compliance\Concerns\HasComplianceUuid;
use App\Models\Compliance\Gap\Concerns\ImmutableModel;
use App\Models\Compliance\Gap\ComplianceGapAssessment;
use App\Models\Compliance\Gap\ComplianceGapFinding;
use App\Models\Project;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A deterministic, explainable remediation recommendation derived from a gap finding
 * (QCIF Sprint 13). Append-only: a recommendation records the exact requirement, gap status,
 * evidence considered, rule, corpus revision, and framework release it was generated from, so it
 * is reproducible. Generated by fixed rules — NEVER by an LLM. UUID is deterministic (uuid5 of
 * requirement + rule + revision) so regeneration is idempotent.
 */
class ComplianceRecommendation extends Model
{
    use HasComplianceUuid;
    use ImmutableModel;

    protected $table = 'compliance_recommendations';

    protected $fillable = [
        'uuid',
        'project_id',
        'framework_release_id',
        'corpus_revision_id',
        'gap_assessment_id',
        'gap_finding_id',
        'requirement_id',
        'control_id',
        'domain_id',
        'recommendation_type',
        'priority',
        'status',
        'title_en',
        'title_ar',
        'description_en',
        'description_ar',
        'rationale_en',
        'rationale_ar',
        'action_items',
        'source_rule',
        'metadata',
    ];

    protected $casts = [
        'priority' => ComplianceRecommendationPriority::class,
        'status' => ComplianceRecommendationStatus::class,
        'action_items' => 'array',
        'metadata' => 'array',
    ];

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class, 'project_id');
    }

    public function frameworkRelease(): BelongsTo
    {
        return $this->belongsTo(ComplianceFrameworkRelease::class, 'framework_release_id');
    }

    public function corpusRevision(): BelongsTo
    {
        return $this->belongsTo(ComplianceCorpusRevision::class, 'corpus_revision_id');
    }

    public function gapAssessment(): BelongsTo
    {
        return $this->belongsTo(ComplianceGapAssessment::class, 'gap_assessment_id');
    }

    public function gapFinding(): BelongsTo
    {
        return $this->belongsTo(ComplianceGapFinding::class, 'gap_finding_id');
    }

    public function requirement(): BelongsTo
    {
        return $this->belongsTo(ComplianceRequirement::class, 'requirement_id');
    }

    public function control(): BelongsTo
    {
        return $this->belongsTo(ComplianceControl::class, 'control_id');
    }

    public function domain(): BelongsTo
    {
        return $this->belongsTo(ComplianceDomain::class, 'domain_id');
    }

    public function actions(): HasMany
    {
        return $this->hasMany(ComplianceRecommendationAction::class, 'recommendation_id')->orderBy('sort_order');
    }
}
